### ISSUE TITLE
List of Parameter Classes for the package

### ISSUE THREAD

**Issue by chidera-ugonwa** [imsujan276/CustomSplashScreen#1]
Can you add a list of parameter classes that can be used in the package?

For example,

Can i increase the size of the image? How?

Can i use a background image? How?

Can i align the image to the bottom? How?

**Comment by imsujan276** [comment]
1. you can increase the logo size by passing the  'logoWidth'. default is 50.
2.  change the background image by passing 'backgroundImage'
3. change background gradient by passing 'gradientBackground'
4. The logo will always be in the center
